# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/
  block:

    - name: CIS | Ensure permissions on system files are configured
      become: true
      ansible.builtin.file:
        name: "{{ item.name }}"
        owner: 'root'
        group: 'root'
        mode: "{{ item.mode }}"
      with_items:
        - {name: '/etc/passwd', mode: '0644'}
        - {name: '/etc/shadow', mode: '0000'}
        - {name: '/etc/group', mode: '0644'}
        - {name: '/etc/gshadow', mode: '0000'}
        - {name: '/etc/group-', mode: '0644'}
        - {name: '/etc/passwd-', mode: '0644'}
        - {name: '/etc/shadow-', mode: '0000'}
        - {name: '/etc/gshadow-', mode: '0000'}

    - name: Set the hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_system'
